config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root to: 'home#index'

  resources :home
  resources :orders
  resources :ordered_items

  get '/all_products', to: 'home#all_products'
  get '/search', to: 'products#search', as: 'search/result'
  get '/search_suggestions', to: 'products#search_suggestions'
  post '/save_user_to_notify', to: 'home#save_user_to_notify'
  delete '/delete_user_notification', to: 'home#delete_user_notification'
  get '/check_coupon', to: 'home#check_coupon'
  delete '/remove_coupon', to: 'home#remove_coupon'
  post '/process_payment', to: 'orders#process_payment'
  get '/show_invoice', to: 'orders#show_invoice'
  put '/store_user_cart', to: 'orders#store_user_cart'
  get '/carts', to: 'carts#index', as: :carts
  post '/add_to_cart', to: 'carts#add_to_cart'
  patch '/update_cart', to: 'carts#update_cart', as: :update_cart
  delete '/remove_cart_item', to: 'carts#remove_cart_item', as: :remove_cart_item

  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  namespace :admin do
    get '/reports', to: 'admin_panels#reports', as: :reports
    post '/admin_panels/reports', to: 'admin_panels#reports'
    post '/search_products', to: 'products#search_products', as: :search_products
    post '/products_search_suggestion', to: 'products#products_search_suggestion', as: :products_search_suggestion
    post '/search_variants', to: 'product_variants#search_variants', as: :search_variants
    post '/variants_search_suggestion', to: 'product_variants#variants_search_suggestion', as: :variants_search_suggestion
    post '/search_orders', to: 'orders#search_orders', as: :search_orders
    post '/orders_search_suggestion', to: 'orders#orders_search_suggestion', as: :orders_search_suggestion

    resources :admin_panels
    resources :discount
    resources :coupon
    resources :banners

    resources :products do
      resources :product_variants
    end

    resources :categories do
      member do
        get :get_subcategories
      end
      resources :sub_categories do
        resources :products do
          resources :product_variants
        end
      end
    end

    resources :orders do
      resources :ordered_items
    end
  end

  resources :categories do
    member do
      get :get_subcategories
    end
    resources :sub_categories do
      resources :products do
        resources :product_variants
      end
    end
    resources :products do
      resources :product_variants
    end
  end

  resources :products do
    resources :product_variants
  end

  resources :sub_categories do
    resources :products
  end
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  enum featured: { no: false, yes: true }
  belongs_to :product
  has_many :ordered_items
  has_many :discounts, as: :discountable
  has_many :notifications
  has_many_attached :product_images
  after_commit :add_default_image, only: [:create, :update]
  after_update_commit :product_back_in_stock

  def product_back_in_stock
    if in_stock_before_last_save.zero?
      self.notifications.each { |item| ProductMailer.send_product_back_in_stock_notification(item.user_id, item.product_variant_id).deliver_later }
      self.notifications.all.delete_all
    end
  end

  def thumbnail(input)
    self.product_images[input].variant(resize: '80x80!').processed
  end

  def tile_photo(input)
    self.product_images[input]
  end

  def final_price
    product = self.product
    categories = Category.where(sub_categories: product.sub_categories)
    min_price = categories.collect { |c| c.discount_price(self) if c.has_valid('Discount') }.compact.min
    min_price = [product.discount_price(self), min_price].min if product.has_valid('Discount')
    [min_price, self.price].compact.min
  end

  private

  def add_default_image
    unless product_images.attached?
      product_images.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'image-not-found.png'
          )
        ),
        filename: 'image-not-found.png',
        content_type: 'image/png'
      )
    end
  end

end

app/controllers/admin/product_variants_controller.rb
class Admin::ProductVariantsController < ApplicationController

  load_and_authorize_resource

  before_action :set_product

  def show
    @product_variant = ProductVariant.find(params[:id])
  end

  def new
    @product_variant = ProductVariant.new
  end

  def create
    @product_variant = @product.product_variants.create(product_variant_params)
    if @product_variant.save
      redirect_to admin_product_path(@product), notice: "New variant added successfully!"
    else
      render :new, alert: 'try again'
    end
  end

  def edit
    @product_variant = @product.product_variants.find(params[:id])
  end

  def update
    if @product_variant.update(product_variant_params)
      redirect_to admin_product_path(@product), notice: 'variant updated Successfully'
    else
      render :edit, notice: 'try again'
    end
  end

  def destroy
    @product_variant = ProductVariant.find(params[:id])
    if @product_variant.destroy
      redirect_to admin_product_path(@product), notice: 'Product Variant Delete Successfully'
    else
      redirect_to admin_product_path(@product), notice: "Something went wrong can't delete now. Try again Please"
    end
  end

  def search_variants
    @product_variants = @product.product_variants.all.where("details iLIKE ?", "%#{params[:search_variants]}%").paginate(page: 1, per_page: 10).order('details ASC')
  end

  def variants_search_suggestion
    search_text = params[:search_text]
    @product_variants = @product.product_variants.all.where("details iLIKE ?", "%#{search_text}%")
    respond_to do |format|
      format.html
      format.json { render json: {product_variants: @product_variants} }
    end
  end

  private

  def product_variant_params
    params.require(:product_variant).permit(:details, :price, :in_stock, :product_id, :purchase_price, :featured, :unit, product_images: [])
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/product_variants_controller.rb
class ProductVariantsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product

  def show
    @product_variant = ProductVariant.find(params[:id])
    @price = @product_variant.price
    @final_price = @product_variant.final_price
    @sub_categories = @product_variant.product.sub_categories
    @products = Product.where(sub_categories: @sub_categories)
    @product_in_cart = current_cart_items&.detect { |el| el.is_a?(Hash) ? (el['product_variant_id'].to_i == @product_variant.id) : (el.product_variant_id == @product_variant.id) }
    @notification = @product_variant.notifications.find_by(user_id: current_user.id) if current_user.present?
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/views/product_variants/show.html.erb
<div id="error_explanation">
  <%= flash[:added_to_cart] %>
</div>

<div class="container">
  <div class="card">
    <div class="container-fluid">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1">
              <%= image_tag(@product_variant.product_images.exists? ? @product_variant.tile_photo(0) : 'image-not-found') %>
            </div>
          </div>
          <ul class="preview-thumbnail nav nav-tabs">
            <% if @product_variant.product_images.count > 1 %>
              <% (1...@product_variant.product_images.count).each do |index| %>
                <li class="active">
                  <%= image_tag(@product_variant.thumbnail(index)) if @product_variant.product_images[index].variable? %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @product_variant.product.title %></h3>
          <p class="product-description"><%= @product_variant.details %></p>
          <br><br>
          <div>
            <i><h5>
              <b>CURRENT PRICE:</b>
              <% if @final_price != @price %>
                <s>
                  <span class="price dollars">
                  <%= formatted_price(@price) %>
                  </span>
                </s> &nbsp&nbsp
              <% end %>
              <span class="price avoid_line_break">
                  <span class="dollars">
                    <%= formatted_price(@final_price) %>
                  </span>
                </span>
            </h5></i>
          </div>
          <br>
          <div class="product-quantity">
            <% if @product_variant.in_stock? %>
              <h5> Available: <%= pluralize(@product_variant.in_stock, @product_variant.unit) %> </h5>
              <% if @product_in_cart.blank? %>
                <%= form_with(scope: :ordered_item, url: add_to_cart_path, local: true, method: :post) do |f| %>
                  <%= f.hidden_field :product_variant_id, value: @product_variant.id %>
                  <%= f.hidden_field :price, value: @product_variant.final_price %>
                  <h5>
                    Quantity:
                    <%= f.number_field :quantity, value: 1, min: 1, step: :any, max: @product_variant.in_stock, style: 'width: 30%;', class: 'avoid_line_break form-control' %>
                  </h5>
                  <%= f.submit "Add To Cart", class: "btn btn-success" %>
                  <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
                <% end %>
              <% else %>
                <% quantity = @product_in_cart.is_a?(Hash) ? @product_in_cart['quantity'] : @product_in_cart.quantity %>
                <%= form_with(scope: :ordered_item, url: update_cart_path, local: true, method: :patch) do |f| %>
                  <%= f.hidden_field :product_variant_id, value: @product_variant.id %>
                  <%= f.hidden_field :price, value: @product_variant.final_price %>
                  Quantity:
                  <%= f.number_field :quantity, value: quantity, min: 1, step: :any, max: @product_variant.in_stock, style: 'width: 30%;', class: 'avoid_line_break form-control' %>
                  </h5>
                  <h5 style="color: #039524"><b><i>Product already in the Cart!</i></b></h5>
                  <%= f.submit "Update Quantity", class: "btn btn-info" %>
                  <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
                <% end %>
              <% end %>
            <% else %>
              <div class="out-of-stock">
                <%= image_tag 'out-of-stock.png', style: 'width:150px; height:150px;' %> <br>
                <div class="back-in-stock">
                  <% if @notification %>
                    <input type="checkbox" id="myCheck" product-id="<%= @product_variant.id %>" checked>
                    <label for="myCheck">Notify me when the product is available.</label>
                  <% else %>
                    <input type="checkbox" id="myCheck" product-id="<%= @product_variant.id %>">
                    <label for="myCheck">Notify me when the product is available.</label>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <% if @product_variant.product.product_variants.count > 1 %>
    <div>
      <div class="col-md-12">
        <table class="table table-bordered table-striped table-hover " style="background-color: #c9c8c8;">
          <tr>
            <th colspan="4" class="center-text">Available Variants</th>
          </tr>
          <tr>
            <th style="text-align: center ">Image</th>
            <th style="text-align: center ">Price</th>
            <th style="text-align: center ">Details</th>
          </tr>
          <% @product_variant.product.product_variants.each do |variant| %>
            <% if variant.id != @product_variant.id %>
              <tr>
                <td style="width: 150px; align-items: center">
                  <%= link_to product_product_variant_path(variant.product_id, variant) do %>
                    <div style="width: 100px; height: 100px;">
                      <%= image_tag(variant.product_images.attached? ? variant.product_images.first : 'image-not-found.png') %>
                    </div>
                  <% end %>
                </td>
                <td style="width: 200px;" class="dollars">
                  <% if variant.final_price != variant.price %>
                    <s><%= formatted_price(variant.price) %></s>
                  <% end %>
                  <%= formatted_price(variant.final_price) %>
                </td>
                <td><%= variant.details %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
  <div class="row"><br></div>
  <h3 align="center">You might also be interested in:</h3>
  <hr>
  <div class="row">
    <% @products.each do |product| %>
      <% if @product_variant.product.id != product.id %>
        <% first_variant = product.product_variants.first %>
        <div class="col-md-2 col-sm-4">
          <div class="product-grid2">
            <%= link_to product_product_variant_path(product, product.product_variants.first) do %>
              <div class="product-image2">
                <%= image_tag(product.product_variants.first.product_images.attached? ? product.product_variants.first.product_images.first : 'image-not-found.png') %>
              </div>
              <div class="product-content">
                <p class="title"><%= product.title.truncate(25, separator: /\s/) %></p>
                <% if first_variant.final_price != first_variant.price %>
                  <s><span class="dollars">
                  <%= formatted_price(first_variant.price) %>
                </span></s>
                  <br>
                <% end %>
                <span class="price">
                  <span class="dollars">
                    <%= formatted_price(first_variant.final_price) %>
                  </span>
                </span>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>