config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root to: 'home#index'

  resources :home
  resources :orders
  resources :ordered_items

  get '/all_products', to: 'home#all_products'
  get '/search', to: 'products#search', as: 'search/result'
  get '/search_suggestions', to: 'products#search_suggestions'
  post '/save_user_to_notify', to: 'home#save_user_to_notify'
  delete '/delete_user_notification', to: 'home#delete_user_notification'
  get '/check_coupon', to: 'home#check_coupon'
  delete '/remove_coupon', to: 'home#remove_coupon'
  post '/process_payment', to: 'orders#process_payment'
  get '/show_invoice', to: 'orders#show_invoice'
  put '/store_user_cart', to: 'orders#store_user_cart'
  get '/carts', to: 'carts#index', as: :carts
  post '/add_to_cart', to: 'carts#add_to_cart'
  patch '/update_cart', to: 'carts#update_cart', as: :update_cart
  delete '/remove_cart_item', to: 'carts#remove_cart_item', as: :remove_cart_item

  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  namespace :admin do
    get '/reports', to: 'admin_panels#reports', as: :reports
    post '/admin_panels/reports', to: 'admin_panels#reports'
    post '/search_products', to: 'products#search_products', as: :search_products
    post '/products_search_suggestion', to: 'products#products_search_suggestion', as: :products_search_suggestion
    post '/search_variants', to: 'product_variants#search_variants', as: :search_variants
    post '/variants_search_suggestion', to: 'product_variants#variants_search_suggestion', as: :variants_search_suggestion
    post '/search_orders', to: 'orders#search_orders', as: :search_orders
    post '/orders_search_suggestion', to: 'orders#orders_search_suggestion', as: :orders_search_suggestion

    resources :admin_panels
    resources :discount
    resources :coupon
    resources :banners

    resources :products do
      resources :product_variants
    end

    resources :categories do
      member do
        get :get_subcategories
      end
      resources :sub_categories do
        resources :products do
          resources :product_variants
        end
      end
    end

    resources :orders do
      resources :ordered_items
    end
  end

  resources :categories do
    member do
      get :get_subcategories
    end
    resources :sub_categories do
      resources :products do
        resources :product_variants
      end
    end
    resources :products do
      resources :product_variants
    end
  end

  resources :products do
    resources :product_variants
  end

  resources :sub_categories do
    resources :products
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :products_sub_categories, dependent: :destroy
  has_many :sub_categories, through: :products_sub_categories
  has_many :product_variants, dependent: :destroy
  has_one :discount, as: :discountable
  has_many :banners
  has_one_attached :brand_image
  accepts_nested_attributes_for :product_variants, reject_if: :all_blank, allow_destroy: true
  PER_PAGE = 10
  attr_accessor :sub_categories
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  load_and_authorize_resource

  def index
    @products = Product.paginate(page: params[:page], per_page: 10).order('title ASC')
  end

  def show
    @product_variants = @product.product_variants.paginate(page: params[:page], per_page: 10)
  end

  def new
    @product = Product.new
    @product.product_variants.build
  end

  def create
    products_sub_category_ids = product_params[:sub_categories].split(',')
    @product = Product.create(product_params)
    products_sub_category_ids.map { |id| @product.products_sub_categories.build(sub_category_id: id) }
    if @product.save
      redirect_to admin_products_path, notice: 'Product Added successfully'
    else
      render :new, notice: 'try again'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: 'Product updated successfully!'
    else
      render :edit, notice: 'try again'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to admin_products_path, notice: 'Product Delete Successfully'
    else
      redirect_to admin_products_path, alert: "Something went wrong can't delete now. Try again Please"
    end
  end

  def search_products
      @products = Product.all.where("title iLIKE ?", "%#{params[:search_products]}%").paginate(page: params[:page], per_page: Product::PER_PAGE).order('title ASC')
  end

  def products_search_suggestion
    search_text = params[:search_text]
    @products = Product.all.where("title iLIKE ?", "%#{search_text}%")
    respond_to do |format|
      format.html
      format.json { render json: {products: @products} }
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :brand_image, :title, :sub_categories,
      product_variants_attributes: [:id, :details, :price, :in_stock, :purchase_price, :_destroy, :featured, :unit, product_images: []])
  end

  def set_sub_category
    @sub_category = SubCategory.find(params[:sub_category_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  load_and_authorize_resource

  def search
    if params[:search].blank?
      redirect_to root_path, notice: "No result found!"
    else
      @parameter = params[:search]
      @products = Product.all.where("title iLIKE ?", "%#{@parameter}%")
      @sub_categories = SubCategory.all.where("title iLIKE ?", "%#{@parameter}%")
      @categories = Category.all.where("title iLIKE ?", "%#{@parameter}%")
    end
  end

  def search_suggestions
    search_text = params[:search_text]
    @products = Product.all.where("title iLIKE ?", "%#{search_text}%")
    @sub_categories = SubCategory.all.where("title iLIKE ?", "%#{search_text}%")
    @categories = Category.all.where("title iLIKE ?", "%#{search_text}%")
    response = { "products" => @products, "categories" => @categories, "sub_categories" => @sub_categories }
    respond_to do |format|
      format.html
      format.json { render json: response }
    end
  end

  def index
    @sub_categories = Category.find(params[:category_id]).sub_categories
    products_sub_categories = ProductsSubCategory.where(sub_category_id: @sub_categories.map(&:id))
    @products = Product.where(products_sub_categories: products_sub_categories)
  end
end

app/views/admin/products/_product_variant_fields.html.erb
<div class="nested-fields">

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :Details, class: "col-form-label-lg mb-0" %>
      <%= f.text_area :details, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-3">
      <%= f.label :Price, class: "col-form-label-lg py-0 mb-0" %>
      <%= f.number_field :price, step: :any, min: 1, class: 'form-control' %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :Purchase_price, class: "col-form-label-lg py-0 mb-0" %>
      <%= f.number_field :purchase_price, step: :any, min: 1, class: 'form-control' %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :Stock_Quantity, class: "col-form-label-lg py-0 mb-0" %>
      <%= f.number_field :in_stock, step: :any, min: 1, class: 'form-control' %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :Unit, class: "col-form-label-lg py-0 mb-0" %>
      <%= f.text_field :unit, class: "form-control" %>
    </div>

  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <strong> <%= f.label :upload_variant_photo %>: </strong>
      <%= f.file_field :product_images, multiple: true %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :featured, class: "col-form-label-lg mb-0" %><br/>
      <%= f.radio_button(:featured, "yes") %>
      <%= label(:featured, "Yes") %>
      <%= f.radio_button(:featured, "no", class: 'ml-3') %>
      <%= label(:featured, "No") %>
    </div>
  </div>

  <%= link_to_remove_association "Remove Variant", f %>
</div>

app/views/admin/products/_search_form.html.erb
<div class="row search-form-wrapper">
  <div class="col-6">
    <%= form_with(url: admin_search_products_path, method: :post, local: true) do |f| %>
      <div class="input-group">
        <%= f.text_field :search_products, id: 'search_products', placeholder: "Search products...", class: "form-control search-input", autocomplete: "off", style: 'margin: 0' %>
        <%= f.submit "Search", class: 'search-bar-btn' %>
      </div>
      <div id="products_search_suggestion">
        <ul id="products_search_suggestion_list"></ul>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="content">
  <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
    <%= form_for @product, url: admin_product_path do |form| %>
      <div class="field" style="width: 50%">
        <%= form.label :Name %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <br>
      <div class="row">
        <div class=" col-md-3 ">
          <%= image_tag(@product.brand_image.attached? ? @product.brand_image : 'image-not-found.png', width: '150px', height: '100px') %>
        </div>
      </div>
      <br>
      <div class="field avoid_line_break" style="width: 30%">
        <strong><%= form.label :Edit_photo %>:</strong>
        <%= form.file_field :brand_image %>
      </div>
      <br>
      <div>
        <br>
        <%= form.submit "Update Product", class: 'btn btn-success' %>
        <%= link_to "Cancel", admin_product_path, class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="content">
  <%= render 'admin/products/search_form' %>
  <div class="row custom-width">
    <div id="user-activity" class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-6">
              <h4 class="card-title" style="display: flex"><i class="fas fa-shopping-bag"></i>All products</h4>
            </div>
            <div class="col-6" style="text-align:right">
              <%= link_to '+ Add Product', new_admin_product_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="table-responsive recentOrderTable">
            <table class="table table-responsive-md">
              <thead>
              <tr>
                <th scope="col">Product Id</th>
                <th scope="col">Product Name</th>
                <th scope="col">Available Variant</th>
                <th scope="col">Action</th>
              </tr>
              </thead>
              <tbody>

              <% @products.each do |product| %>
                <td><%= product.id %></td>
                <td><%= product.title %></td>
                <td><%= product.product_variants.count %></td>
                <td>
                  <%= link_to admin_product_path(product) do %>
                    <i class="far fa-eye" title="Show Variants"></i>
                  <% end %>
                  |
                  <%= link_to edit_admin_product_path(product) do %>
                    <i class="fas fa-edit" title="Edit"></i>
                  <% end %>
                  |
                  <%= link_to admin_product_path(product), method: :delete, data: {confirm: 'Are you sure? All the details of the product will be also deleted'} do %>
                    <i class="fas fa-trash-alt" title="Delete"></i>
                  <% end %>
                </td>
                </tr>
              <% end %>
              <tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="digg_pagination apple_pagination">
        <div class="page_info">
          <%= page_entries_info @products, model: 'Product' %>
        </div>
        <%= will_paginate @products, :container => false %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/products/new.html.erb
<div class="content">
  <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
    <div class="card">
      <h3 align="center">Add Product</h3>
      <hr>
      <br>
      <div class="form-row">

        <div class="form-group col-md-6">
          <label class="col-form-label-lg mb-0">Category</label>
          <%= select_tag :categories, options_from_collection_for_select(Category.all, :id, :title), { prompt: "Choose a category", id: "category_select", class: 'form-control'} %>
        </div>

        <div class="form-group col-md-6">
          <label class="col-form-label-lg mb-0">Subcategory</label>
          <span id="subcategories_select" class="d-flex">
              <%= select_tag :sub_categories, options_from_collection_for_select({}, :id, :title), { prompt: "Choose a subcategory", id: 'sub_category-select', disabled: true, class: 'form-control'} %>
            <button id="select-subcategory" disabled class="btn btn-primary w-25 m-0 ml-2">Add</button>
            </span>
        </div>

      </div>
      <%= form_for @product, url: admin_products_path do |form| %>

        <div class="form-row">
          <div class="col-md-6"></div>
          <div class="form-group col-md-6">
            <div id="category-id"></div>
          </div>
        </div>

        <%= form.hidden_field :sub_categories, class: 'form-control', id:"hidden_sub_categories" %>

        <div class="form-row">
          <div class="form-group col-md-12">
            <%= form.label :Name, class: "col-form-label-lg mb-0 py-0" %>
            <%= form.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-12">
            <strong><%= form.label :Upload_brand_photo %>:</strong>
            <%= form.file_field :brand_image %>
          </div>
        </div>

        <div class="nested-attributes-div">
          <%= form.fields_for :product_variants do |variant| %>
            <%= render 'product_variant_fields', f: variant %>
          <% end %>
          <div class="links">
            <%= link_to_add_association "Add Variant", form, :product_variants %>
          </div>
        </div>

        <%= form.submit "Add Product", class: "btn btn-primary mt-3" %>
        <%= link_to "Cancel", :back, class: "btn btn-danger mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/search_products.html.erb
<div class="content">
  <%= render 'admin/products/search_form' %>
  <div class="row custom-width">
    <div id="user-activity" class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-6">
              <h4 class="card-title" style="display: flex"><i class="fas fa-shopping-bag"></i>All products</h4>
            </div>
            <div class="col-6" style="text-align:right">
              <%= link_to '+ Add Product', new_admin_product_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="table-responsive recentOrderTable">
            <table class="table table-responsive-md">
              <thead>
              <tr>
                <th scope="col">Product Id</th>
                <th scope="col">Product Name</th>
                <th scope="col">Available Variant</th>
                <th scope="col">Action</th>
              </tr>
              </thead>
              <tbody>

              <% @products.each do |product| %>
                <td><%= product.id %></td>
                <td><%= product.title %></td>
                <td><%= product.product_variants.count %></td>
                <td>
                  <%= link_to admin_product_path(product) do %>
                    <i class="far fa-eye" title="Show Variants"></i>
                  <% end %>
                  |
                  <%= link_to edit_admin_product_path(product) do %>
                    <i class="fas fa-edit" title="Edit"></i>
                  <% end %>
                  |
                  <%= link_to admin_product_path(product), method: :delete, data: {confirm: 'Are you sure? All the details of the product will be also deleted'} do %>
                    <i class="fas fa-trash-alt" title="Delete"></i>
                  <% end %>
                </td>
                </tr>
              <% end %>
              <tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="digg_pagination apple_pagination">
        <div class="page_info">
          <%= page_entries_info @products, model: 'Product' %>
        </div>
        <%= will_paginate @products, :container => false %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/admin/products/show.html.erb
<div class="content">
  <%= render 'admin/product_variants/variants_search_form' %>
  <div class="row custom-width">
    <div id="user-activity" class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
      <div class="card">
        <div class="card-header">
          <div class="row">
            <div class="col-8">
              Product variants for: <h4 class="card-title" product_id="<%= @product.id %>" id="product_info" style="display: flex"><%= @product.title %></h4>
            </div>
            <div class="col-4">
              <%= link_to '+ Add Variant', new_admin_product_product_variant_path(@product), class: "btn btn-primary float-right" %>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="table-responsive recentOrderTable">
            <table class="table table-responsive-md">
              <thead>
              <tr>
                <!--                <th scope="col">Thumbnail</th>-->
                <th scope="col">Product details</th>
                <th scope="col">In stock</th>
                <th scope="col">Purchase Price</th>
                <th scope="col">Selling Price</th>
                <th scope="col">Action</th>
              </tr>
              </thead>
              <tbody>
              <% @product_variants.each do |product_variant| %>
                <tr>
                  <!--                <td><%#= image_tag(product_variant.product_images.first, class: 'circular-image')%></td>-->
                  <td><%= product_variant.details %></td>
                  <td><%= pluralize(product_variant.in_stock,product_variant.unit) %> </td>
                  <td class="dollars"><%= formatted_price(product_variant.purchase_price)%></td>
                  <td class="dollars"><%= formatted_price(product_variant.price) %></td>

                  <td>
                    <%#= link_to admin_product_product_variant_path(@product, product_variant) do %>
                    <!--                    <i class="far fa-eye" title="Show Variants"></i>-->
                    <%# end %>
                    <!--                  |-->
                    <%= link_to edit_admin_product_product_variant_path(@product, product_variant) do %>
                      <i class="far fa-edit" title="Edit Variant"></i>
                    <% end %>
                    |
                    <%= link_to admin_product_product_variant_path(@product, product_variant), method: :delete, data: {confirm: 'Are you sure?'} do %>
                      <i class="far fa-trash-alt" title="Delete Variant"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="digg_pagination apple_pagination">
        <div class="page_info">
          <%= page_entries_info @product_variants, model: 'ProductVariant' %>
        </div>
        <%= will_paginate @product_variants, :container => false %>
      </div>
    </div>
  </div>
</div>
</div>