config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  root to: 'home#index'

  resources :home
  resources :orders
  resources :ordered_items

  get '/all_products', to: 'home#all_products'
  get '/search', to: 'products#search', as: 'search/result'
  get '/search_suggestions', to: 'products#search_suggestions'
  post '/save_user_to_notify', to: 'home#save_user_to_notify'
  delete '/delete_user_notification', to: 'home#delete_user_notification'
  get '/check_coupon', to: 'home#check_coupon'
  delete '/remove_coupon', to: 'home#remove_coupon'
  post '/process_payment', to: 'orders#process_payment'
  get '/show_invoice', to: 'orders#show_invoice'
  put '/store_user_cart', to: 'orders#store_user_cart'
  get '/carts', to: 'carts#index', as: :carts
  post '/add_to_cart', to: 'carts#add_to_cart'
  patch '/update_cart', to: 'carts#update_cart', as: :update_cart
  delete '/remove_cart_item', to: 'carts#remove_cart_item', as: :remove_cart_item

  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  namespace :admin do
    get '/reports', to: 'admin_panels#reports', as: :reports
    post '/admin_panels/reports', to: 'admin_panels#reports'
    post '/search_products', to: 'products#search_products', as: :search_products
    post '/products_search_suggestion', to: 'products#products_search_suggestion', as: :products_search_suggestion
    post '/search_variants', to: 'product_variants#search_variants', as: :search_variants
    post '/variants_search_suggestion', to: 'product_variants#variants_search_suggestion', as: :variants_search_suggestion
    post '/search_orders', to: 'orders#search_orders', as: :search_orders
    post '/orders_search_suggestion', to: 'orders#orders_search_suggestion', as: :orders_search_suggestion

    resources :admin_panels
    resources :discount
    resources :coupon
    resources :banners

    resources :products do
      resources :product_variants
    end

    resources :categories do
      member do
        get :get_subcategories
      end
      resources :sub_categories do
        resources :products do
          resources :product_variants
        end
      end
    end

    resources :orders do
      resources :ordered_items
    end
  end

  resources :categories do
    member do
      get :get_subcategories
    end
    resources :sub_categories do
      resources :products do
        resources :product_variants
      end
    end
    resources :products do
      resources :product_variants
    end
  end

  resources :products do
    resources :product_variants
  end

  resources :sub_categories do
    resources :products
  end
end

app/views/admin/admin_panels/_admin_nav.html.erb
<div class="sidebar" style="background-color: #e3f2fd; width:200px">
  <%= active_link_to "Dashboard", admin_admin_panels_path %>
  <%= active_link_to "Reports", admin_reports_path %>
  <%= active_link_to "Orders", admin_orders_path %>
  <%= active_link_to "Banners", admin_banners_path %>
  <%= active_link_to "Categories", admin_categories_path %>
  <%= active_link_to "Products", admin_products_path %>
  <%= active_link_to "Set Discount", admin_discount_index_path %>
  <%= active_link_to "Create Coupon", admin_coupon_index_path %>
</div>

app/views/admin/admin_panels/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-8 col-xxl-8 col-lg-8 col-md-12">
        <div id="user-activity" class="card">
          <div class="card-header">
            <h4 class="card-title">Statistics</h4>
            <div class="card-action">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active viewSwitch" data-toggle="tab" href="#day" role="tab">Day</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link viewSwitch" data-toggle="tab" href="#week" role="tab">Week</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link viewSwitch" data-toggle="tab" href="#month" role="tab">Month</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="card-body">
            <div class="tab-content mt-5" id="myTabContent">
              <div id="day">
                <%= line_chart [{ name: 'User', data: User.group_by_day(:created_at).count },
                                { name: 'Order', data: Order.group_by_day(:created_at).count },
                                { name: 'Product', data: Product.group_by_day(:created_at).count }], refresh: 120 %>
              </div>
              <div id="week">
                <%= line_chart [{ name: 'User', data: User.group_by_week(:created_at).count },
                                { name: 'Order', data: Order.group_by_week(:created_at).count },
                                { name: 'Product', data: Product.group_by_week(:created_at).count }], refresh: 120 %>
              </div>
              <div id="month">
                <%= line_chart [{ name: 'User', data: User.group_by_month(:created_at).count },
                                { name: 'Order', data: Order.group_by_month(:created_at).count },
                                { name: 'Product', data: Product.group_by_month(:created_at).count }], refresh: 120 %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-4 col-xxl-4 col-lg-4 col-md-12">
        <div class="row">
          <div class="col-lg-12 col-md-4">
            <div class="widget-stat card">
              <div class="card-body">
                <div class="media ai-icon">
                  <span class="mr-3">
                    <svg id="icon-customers" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
                      <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" style="stroke-dasharray: 25, 45; stroke-dashoffset: 0;"></path>
                      <path d="M8,7A4,4 0,1,1 16,7A4,4 0,1,1 8,7" style="stroke-dasharray: 26, 46; stroke-dashoffset: 0;"></path>
                    </svg>
                  </span>
                  <div class="media-body">
                    <p class="mb-1">Customers</p>
                    <h4 class="mb-0"><%= User.count %></h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-12 col-md-4">
            <div class="widget-stat card">
              <div class="card-body">
                <div class="media ai-icon">
                  <span class="mr-3">
                    <svg id="icon-orders" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
                      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" style="stroke-dasharray: 66, 86; stroke-dashoffset: 0;"></path>
                      <path d="M14,2L14,8L20,8" style="stroke-dasharray: 12, 32; stroke-dashoffset: 0;"></path>
                      <path d="M16,13L8,13" style="stroke-dasharray: 8, 28; stroke-dashoffset: 0;"></path>
                      <path d="M16,17L8,17" style="stroke-dasharray: 8, 28; stroke-dashoffset: 0;"></path>
                      <path d="M10,9L9,9L8,9" style="stroke-dasharray: 2, 22; stroke-dashoffset: 0;"></path>
                    </svg>
                  </span>
                  <div class="media-body">
                    <p class="mb-1">Orders</p>
                    <h4 class="mb-0"><%= @order.count %></h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xl-8 col-lg-8 col-md-8">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title" style="display: flex"><i class="fas fa-shopping-bag"></i> &nbsp;Recent Orders</h4>
            <h4 class="card-title" style="display: inline; "><%= link_to 'All Orders', admin_products_path %></h4>
          </div>
          <div class="card-body">
            <div class="table-responsive recentOrderTable">
              <table class="table table-responsive-md">
                <thead>
                <tr>
                  <th scope="col">Order Id</th>
                  <th scope="col">Customer Name</th>
                  <th scope="col">Status</th>
                  <th scope="col">Total</th>
                  <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <% @order.last(10).reverse_each do |order| %>
                  <td><%= order.id %></td>
                  <td><%= order.user.first_name %> <%= order.user.last_name %></td>
                  <td>Delivered</td>
                  <td class="dollars"><%= formatted_price(order.total) %></td>
                  <td>
                    <%= link_to admin_order_ordered_items_path(order) do %>
                      <i class="far fa-eye" title="Show Invoice"></i>
                    <% end %>
                  </td>
                  </tr>
                <% end %>
                <tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admin_panels/reports.html.erb
<div class="content">
  <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12">
    <div id="user-activity" class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-md-6">
            <h5>Revenue</h5>
          </div>
          <div class="col-md-6">
            Search by a custom date:
            <div class="row">
              <div class="col-md-5">
                <input class="form-control date-form" type="date" value="<%= Date.today %>" id="revenue-start-date" >
              </div>
              <div class="col-md-5">
                <input class="form-control date-form" type="date" value="<%= Date.tomorrow %>" id="revenue-end-date" >
              </div>
              <div class="col-md-2">
                <span class="btn" id="revenue_search_btn"> <i class="fa fa-search" aria-hidden="true"></i> </span>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div class="row revenue_by_custom_date">
        <br>
        <div class="card-body">
          <div class="media-body col-md-12">
            <h4 align="center" class="dollars revenue"> </h4>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="col-md-4">
          <div class="widget-stat card">
            <div class="card-body">
              <div class="media ai-icon">
            <span class="mr-3">
              <i class="fas fa-money-bill-wave"></i>
            </span>
                <p class="mb-1">Today</p>
              </div>
            </div>
            <div>
              <h4 align="center" class="dollars"><%= formatted_price((OrderedItem.to_day.sum("price*quantity") - OrderedItem.to_day.sum("purchase_price*quantity"))) %></h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="widget-stat card">
            <div class="card-body">
              <div class="media ai-icon">
            <span class="mr-3">
              <i class="fas fa-money-bill-wave"></i>
            </span>
                <p class="mb-1">This Month</p>
              </div>
            </div>
            <div class="media-body">
              <h4 align="center" class="dollars"><%= formatted_price(OrderedItem.this_month.sum("price*quantity") - OrderedItem.this_month.sum("purchase_price*quantity")) %></h4>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="widget-stat card">
            <div class="card-body">
              <div class="media ai-icon">
             <span class="mr-3">
              <i class="fas fa-money-bill-wave"></i>
            </span>
                <p class="mb-1">This Year</p>
              </div>
            </div>
            <div class="media-body">
              <h4 align="center" class="dollars"><%= formatted_price((OrderedItem.this_year.sum("price*quantity") - OrderedItem.this_year.sum("purchase_price*quantity")))  %></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xl-6 col-xxl-6 col-lg-6 col-md-12">
      <div id="user-activity" class="card">
        <div class="card-header">
          <h5>Top Sold Products</h5> <br>
          <div class="card-action">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active viewSwitch" data-toggle="tab" href="#day" role="tab">
                  Day
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link viewSwitch" data-toggle="tab" href="#week" role="tab">
                  Week
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link viewSwitch" data-toggle="tab" href="#month" role="tab">
                  Month
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div class="card-body">
          <div class="tab-content mt-5" id="myTabContent">
            <div id="day">
              <%= column_chart @today_top_twenty_product %>
            </div>
            <div id="week">
              <%= column_chart @this_week_top_twenty_product %>
            </div>
            <div id="month">
              <%= column_chart @this_month_top_twenty_product %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-6 col-xxl-6 col-lg-6 col-md-12">
      <div id="user-activity" class="card">
        <div class="card-header">
          <h5>This Month Top Sold Products</h5> <br>
        </div>
        <div>
          <ol>
            <% @this_month_top_twenty_product.each do |product| %>
              <% if ProductVariant.exists?(id: product.first) %>
              <li><%= ProductVariant.find(product.first).product.title %> <b>/</b>
                <%= ProductVariant.find(product.first).details %>
              </li>
                <% end %>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>